name: mm-benchcat

services:
  mongodb:
    container_name: mm-benchcat-mongodb
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./data/mongodb:/data:Z

  neo4j:
    container_name: mm-benchcat-neo4j
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - ./data/neo4j/logs:/logs:Z
      - ./data/neo4j/data:/data:Z

  postgresql:
    container_name: mm-benchcat-postgresql
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql:Z
