# Default configuration file. To override this file, create 'application.properties' file in the same directory.

mongodb.host=localhost
mongodb.port=27017
mongodb.authDatabase=admin
mongodb.database=mongo
mongodb.username=
mongodb.password=

neo4j.host=localhost
neo4j.port=7687
neo4j.database=neo4j
neo4j.username=neo4j
neo4j.password=

postgresql.host=localhost
postgresql.port=5432
postgresql.database=postgres
postgresql.username=postgres
postgresql.password=
