# Default configuration file. To override this file, create 'application.properties' file in the same directory.

neo4j.host=localhost
neo4j.port=7687
neo4j.database=neo4j
neo4j.username=neo4j
neo4j.password=
